const DATABASE_PASSWORD = 'password';
const JWT_EXPIRY_SECONDS = 900;
const ENDPOINT_ZIP_MAX_MEGABYTES = 50;

exports.DATABASE_PASSWORD = DATABASE_PASSWORD;
exports.JWT_EXPIRY_SECONDS = JWT_EXPIRY_SECONDS;
exports.ENDPOINT_ZIP_MAX_MEGABYTES = ENDPOINT_ZIP_MAX_MEGABYTES;
