const DATABASE_PASSWORD = 'password';
const JWT_EXPIRY_SECONDS = 900;
const ENDPOINT_ZIP_MAX_MEGABYTES = 50;
const ENDPOINT_RESPONSE_MILLISECONDS = 1000;
const JWT_SECRET = "1234567890";
const RATE_LIMIT_DURATION_MILLISECONDS = 6000;
const RATE_LIMIT_COUNT = 100;
const RATE_LIMIT_MAX_DATE_TRACKING = 100000;

exports.DATABASE_PASSWORD = DATABASE_PASSWORD;
exports.JWT_EXPIRY_SECONDS = JWT_EXPIRY_SECONDS;
exports.ENDPOINT_ZIP_MAX_MEGABYTES = ENDPOINT_ZIP_MAX_MEGABYTES;
exports.ENDPOINT_RESPONSE_MILLISECONDS = ENDPOINT_RESPONSE_MILLISECONDS;
exports.JWT_SECRET = JWT_SECRET;
exports.RATE_LIMIT_DURATION_MILLISECONDS = RATE_LIMIT_DURATION_MILLISECONDS;
exports.RATE_LIMIT_COUNT = RATE_LIMIT_COUNT;
exports.RATE_LIMIT_MAX_DATE_TRACKING = RATE_LIMIT_MAX_DATE_TRACKING;
